// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyvBg1yk_NOPJ4wQHfoUYxqLg9n4lq2xQ',
    appId: '1:701077215139:web:2c48332d84ad0862c2ec16',
    messagingSenderId: '701077215139',
    projectId: 'fir-auth-f23d3',
    authDomain: 'fir-auth-f23d3.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-957bb.appspot.com',
  );
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyvBg1yk_NOPJ4wQHfoUYxqLg9n4lq2xQ',
    appId: '1:701077215139:android:a2d79a44108879a4c2ec16',
    messagingSenderId: '701077215139',
    projectId: 'fir-auth-f23d3',
    storageBucket: 'fir-auth-f23d3.appspot.com',
  );
}
